name: export-branch-dev
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-branch-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ secrets.dev_url }}
        user-name: ${{ secrets.dev_username }}
        password-secret: ${{ secrets.dev_password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ secrets.dev_url }}
        user-name: ${{ secrets.dev_username }}
        password-secret: ${{ secrets.dev_password }}
        solution-name: AXIRPA
        solution-output-file: out/exported/AXIRPA.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/AXIRPA.zip
        solution-folder: out/solutions/AXIRPA
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/AXIRPA
        solution-target-folder: solutions/AXIRPA
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: false
