name: release-test
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    # - name: Update solution version
    #   uses: update-solution-version
    #   with:
    #     patch-version: # Hoe kom ik hier aan het versienummer?

    - name: Verify connection with Development Environment
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ secrets.dev_url }}
        user-name: ${{ secrets.dev_username }}
        password-secret: ${{ secrets.dev_password }}

    - name: Pack Solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: solutions/AXIRPA
        solution-file: out/solutions/AXIRPA.zip
        solution-type: Unmanaged

    - name: Import Solution
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ secrets.dev_url }}
        user-name: ${{ secrets.dev_username }}
        password-secret: ${{ secrets.dev_password }}
        solution-file: out/solutions/AXIRPA.zip
        force-overwrite: true
        publish-changes: true

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ secrets.dev_url }}
        user-name: ${{ secrets.dev_username }}
        password-secret: ${{ secrets.dev_password }}
        solution-name: AXIRPA
        managed: true
        solution-output-file: out/ship/AXIRPA.zip

    - name: Upload Solution to GitHub Artifact Store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/ship/AXIRPA.zip

  release-to-staging:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch Solution from GitHub Artifact Store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/

    - run: get-childitem .\out\release\

    - name: Verify connection with Test environment
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ secrets.test_url }}
        user-name: ${{ secrets.test_username }}
        password-secret: ${{ secrets.test_password }}

    - name: Replace AXI ERP URL environment variable
      uses: datamonsters/replace-action@v2
      with:
        files: "axirpa_axi_erp_solutions_url.xml"
      replacements: '${{dev_axirpa_url}}=${{test_axirpa_url}}'

    - name: Replace AXI ERP Username environment variable
      uses: datamonsters/replace-action@v2
      with:
        files: "axirpa_axi_erp_solutions_username.xml"
        replacements: '${{dev_axirpa_username}}=${{test_axirpa_username}}'

    - name: Replace AXI ERP Password environment variable
      uses: datamonsters/replace-action@v2
      with:
        files: "axirpa_axi_erp_solutions_password.xml"
        replacements: '${{dev_axirpa_password}}=${{test_axirpa_password}}'

    - name: Import Solution To Test
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ secrets.test_url }}
        user-name: ${{ secrets.test_username }}
        password-secret: ${{ secrets.test_password }}
        solution-file: out/release/AXIRPA.zip
        force-overwrite: false
        publish-changes: true