name: release-test
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: solutions/AXIRPA
        solution-file: out/solutions/AXIRPA.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: '${{ $secrets.dev_url }}'
        user-name: '${{ $secrets.dev_username }}'
        password-secret: ${{ secrets.dev_password }}
        solution-file: out/solutions/AXIRPA.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: '${{ $secrets.dev_url }}'
        user-name: '${{ $secrets.dev_username }}'
        password-secret: ${{ secrets.dev_password }}
        solution-name: AXIRPA
        managed: true
        solution-output-file: out/ship/AXIRPA.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/ship/AXIRPA.zip

  release-to-staging:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/

    - run: get-childitem .\out\release\

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: '${{ $secrets.test_url }}'
        user-name: '${{ $secrets.test_username }}'
        password-secret: ${{ secrets.test_password }}
        solution-file: out/release/AXIRPA.zip
        force-overwrite: true
        publish-changes: true